### ISSUE TITLE
Talent Frame Scale Reseting

### ISSUE THREAD

**Issue by lowpita** [Numynum/TalentLoadoutManager#2]
Hey. When enabling this addon and talent tree tweaks one together, while using the scale talent frame option, it resets back to default every new session, same with reloading. So I have to close then re-open the talent frame for it to scale down or up to what I set it to before. I think this is happening because the "auto scale" option in the manager addon is enabled by default which we can't disable.
This is what my settings are looking like: 
https://imgur.com/FX8Q3Yn
https://imgur.com/wawGbr2

**Comment by Numynum** [comment]
thanks for letting me know 
I'll fix it, but for now you can disable talent tree tweaks, change the settings, and enable the addon again, and it should work fine :)

**Comment by lowpita** [comment]
Thanks for the quick response :) Also I'd like to suggest if we can have a transparecy mode for the manager addon tab in the talent frame like we have in the tweaks addon.

**Comment by Numynum** [comment]
I'm planning to sync the transparency with the setting from TTT 🙂

**Comment by lowpita** [comment]
Ok. Thanks again :)

**Comment by Numynum** [comment]
the scale should now no longer reset anymore 🙂
transparency will probably have to wait until the weekend 👌
