### ISSUE TITLE
Loadouts not loading and causing error

### ISSUE THREAD

**Issue by picklerick84** [Numynum/TalentLoadoutManager#3]
I get this error whenever I login or reload on any toon.  I also can't select any of my loadouts saved in the manager, I have to select the "TalentLoadoutManager" loadout from the default ui, then I can select, but it still doesn't seem to be loading them until I sometimes select one twice.  I'm not sure whats going on with it.  If I had a loadout from this manager used before my last logout, it also will go to the blizz default loadout instead of what I had.

I'm using version 0.3.3 and if I only disable this addon, the error goes away.  I'm not sure why it references weakauras in this error.  Unless when you login this addon calls weakauras.lua.  

35x invalid key to 'next'
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@SharedXML/GlobalCallbackRegistry.lua"]:9: in function <SharedXML/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: in function `resume'
[string "@WeakAuras/WeakAuras.lua"]:1189: in function `Login'
[string "@WeakAuras/WeakAuras.lua"]:1273: in function <WeakAuras/WeakAuras.lua:1224>

Locals:
(*temporary) = <table> {
 99 = <function> defined @SharedXML/EventUtil.lua:66
 101 = <function> defined @SharedXML/EventUtil.lua:66
 103 = <function> defined @SharedXML/EventUtil.lua:66
 105 = <function> defined @SharedXML/EventUtil.lua:66
 100 = <function> defined @SharedXML/EventUtil.lua:66
 102 = <function> defined @SharedXML/EventUtil.lua:66
 107 = <function> defined @SharedXML/EventUtil.lua:66
}
(*temporary) = <function> defined @SharedXML/CallbackRegistry.lua:142
(*temporary) = "Blizzard_ClassTalentUI"
(*temporary) = 104

**Comment by Numynum** [comment]
do you also get that error if TalentLoadoutManager is the only addon enabled?
I haven't seen that error myself, even after deleting all settings and setting things up from scratch

TLM should automatically set the TalentLoadoutManager loadout as active, and then apply the custom loadout (this is to ensure your actionbars for the TLM custom loadouts are always consistent; if blizzard fixes a bug, then it could be optimized into only switching talents once)
there was a small issue, that the custom loadout wouldn't be automatically applied, I've fixed that in the latest version, though the custom loadout should already have been fully loaded (just with the UI waiting for you to press the Apply Changes button)

it's quite likely that a badly written addon will interfere with TLM and cause any number of bugs though; but in testing, I've not had any issues myself

**Comment by picklerick84** [comment]
No, I haven't tried it with only TalentLoadoutManager enabled, I've been using it for a couple weeks now and it's worked fine with other addons enabled with it.  

I haven't changed any other addons and if I revert this addon to version 0.2.2, it works perfectly fine again.  If I update it to version 0.3.0, it starts giving the same error again.  So it's something that has changed from version 0.2.2 to 0.3.0.

It's a great addon and I hope you'll look into it.  I'm also not the only one getting this issue, there is the same complaint on the curseforge page.  It has to do with something that was changed going to 0.3.0

**Comment by Numynum** [comment]
hm okay..
well unfortunately, almost everything got changed significantly in 0.3.0, so it's like finding a needle in a haystack 😕

the error from the guy on CF implies there's _something_ bugging out when the talent UI is loaded
but your error seems to be happening on login, is that right?

**Comment by Numynum** [comment]
ah yes, you said it happens whenever you log in
some addon (or weakaura maybe 🤔) is loading the talent UI on login, which it shouldn't really be doing, since that's known to give issues (the easiest to spot, is the loadout dropdown showing the wrong loadout)

**Comment by picklerick84** [comment]
I use elvui and some other addons.  The only weakaura I could think that would do anything with the talent ui would be Chonky Character Sheet https://wago.io/bRl2gJIgz, but I have it to not load talents unless I open my character sheet and open the talent tab.

I reverted to 0.2.2 now and it seems to be working fine again though, as soon as I go up to 0.3.0 it starts again

**Comment by picklerick84** [comment]
I put that weakaura to load never and it still gives the same error, except it no longer gives the error when I login, it gives the error when I open my talent page.

It also has the wrong talent loadout in the dropdown regardless, even if I reload ui, it goes back to wrong talents in dropdown

**Comment by Numynum** [comment]
I made quite a few changes in the new release just now, the "invalid key to 'next'" error should be fixed (I hope)

there were also some changes to how blizzard loadouts are switched, including some changes to the dropdown

could you install the new release, and let me know if you still encounter any issues, that'd be very helpful 🙂

**Comment by picklerick84** [comment]
Ok.  I will when its available, its not showing up on curseforge yet at least

**Comment by picklerick84** [comment]
Nevermind.  I just downloaded the zip and installed it.  It seems to be working perfect now, I haven't relogged yet because I'm about to start a key, but on reload it didn't give any errors or when I opened talents

**Comment by Numynum** [comment]
curseforge is always a bit delayed yes
good to know that the main issue is fixed ^^

if you find any others, feel free to open another issue 👌

**Comment by picklerick84** [comment]
Sounds good. Thank you
