### ISSUE TITLE
Can't load DK talent sets 

### ISSUE THREAD

**Issue by FireSock94** [Numynum/TalentLoadoutManager#6]
Hi, i have a problem loading talent sets on my DK, if the talent Unholy Pact is skilled. 
If I try loading a set with that talent i get the message "Faild to fully apply loadout. 10 entries could not be purchsed." 
I try loading a set without Unholy Pact and its load without any problems. 

If there is anything i should provided to help find the issue, please let me know.

Thanks for the addon and the work and thanks in advance for looking in the issue.

**Comment by Numynum** [comment]
It turns out blizzard has some broken data for that talent, which made this addon think it was a choice node.
I fixed the choice node detection code, and that seems to have fixed it 🙂
